READ_ACTIONS.add("companyPeriods");
function renderScheduleWarnings(data){let host=$("#adminScheduleWarning");if(!host){host=document.createElement("p");host.id="adminScheduleWarning";host.className="inline-notice";$("#adminRows").closest("table").insertAdjacentElement("beforebegin",host);}host.hidden=!(data.scheduleWarnings||[]).length;host.textContent=(data.scheduleWarnings||[]).join(" ");}
let companyPeriods=[],editingCompanyPeriod=null;
const companyHost=document.createElement("details");companyHost.innerHTML=html`<summary>Orario aziendale a periodi</summary><p>Standard: 8h lun–ven. Le eccezioni individuali prevalgono. Nessun periodo estivo 2026 è inserito automaticamente. Le modifiche ricalcolano le segnalazioni e non cambiano le ore registrate.</p><button id="loadCompanyPeriods" type="button">Carica periodi</button><form id="companyPeriodForm"><div class="complexity-fields"><label>Nome<input name="nome" maxlength="80" required></label><label>Data inizio<input name="inizio" type="date" required></label><label>Data fine<input name="fine" type="date" required></label></div><div id="companyPeriodWeek" class="complexity-fields">${WORK_DAYS.map((day,i)=>html`<label>${day}<input data-company-week="${i}" value="${i<5?"8h":"0h"}" required></label>`)}</div><label>Motivo modifica (obbligatorio per periodi passati)<input name="motivo" maxlength="500"></label><button type="submit">Salva periodo</button><button id="newCompanyPeriod" type="button">Nuovo periodo</button></form><div class="table-wrap"><table><thead><tr><th>Nome / date</th><th>Ore lun–dom</th><th>Azioni</th></tr></thead><tbody id="companyPeriodRows"></tbody></table></div>`;$("#adminPanel").appendChild(companyHost);
function fillCompanyPeriod(period,duplicate=false){
 const form=$("#companyPeriodForm");editingCompanyPeriod=duplicate?null:period;
 form.elements.nome.value=period?.nome||"";form.elements.inizio.value=duplicate?"":period?.data_inizio||"";form.elements.fine.value=duplicate?"":period?.data_fine||"";form.elements.motivo.value="";
 for(const input of form.querySelectorAll("[data-company-week]"))input.value=fmtMinutes(period?.settimana_minuti?.[Number(input.dataset.companyWeek)]??(Number(input.dataset.companyWeek)<5?480:0));
 form.elements.nome.focus();if(duplicate)notify("Ore copiate. Inserisci e verifica le nuove date prima di salvare.","ok");
}
async function loadCompanyPeriods(){try{const data=await api("companyPeriods");companyPeriods=data.rows||[];$("#companyPeriodRows").innerHTML=html`${companyPeriods.map(p=>html`<tr><td>${p.nome}<br>${archiveDate(p.data_inizio)} → ${archiveDate(p.data_fine)}</td><td>${p.settimana_minuti.map(fmtMinutes).join(" · ")}</td><td><button data-period-edit="${p.id}">Modifica</button><button data-period-copy="${p.id}">Duplica per nuovo anno</button></td></tr>`)}`;
 for(const button of $("#companyPeriodRows").querySelectorAll("button"))button.addEventListener("click",()=>fillCompanyPeriod(companyPeriods.find(p=>p.id===(button.dataset.periodEdit||button.dataset.periodCopy)),!!button.dataset.periodCopy));
 }catch(e){notify(e.message);}}
$("#loadCompanyPeriods").addEventListener("click",loadCompanyPeriods);$("#newCompanyPeriod").addEventListener("click",()=>fillCompanyPeriod(null));
$("#companyPeriodForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,week=[...form.querySelectorAll("[data-company-week]")].map(input=>inputMinutes(input.value));if(week.some(m=>m===null)){notify("Controlla le durate settimanali.","warn");return;}const button=form.querySelector('[type="submit"]');button.disabled=true;try{await api("saveCompanyPeriod",{id:editingCompanyPeriod?.id||null,updatedAt:editingCompanyPeriod?.updated_at||null,nome:form.elements.nome.value,dataInizio:form.elements.inizio.value,dataFine:form.elements.fine.value,settimanaMinuti:week,motivo:form.elements.motivo.value});notify("Periodo salvato. Le ore registrate restano invariate.","ok");fillCompanyPeriod(null);await loadCompanyPeriods();await loadDay();}catch(error){notify(error.message);}finally{button.disabled=false;}});
