READ_ACTIONS.add("dataQuality");
const qualityHost=document.createElement("details");qualityHost.id="qualityPanel";
qualityHost.innerHTML=html`<summary>Qualità dati</summary><p>Segnalazioni da verificare: nessuna correzione o esclusione automatica. I conteggi riguardano tutto lo storico e non includono l’account test.</p><p>Giornate oltre 12h: ore rendicontate, assenze incluse e indicate separatamente. Attività CRM: età dalla creazione della segnalazione. Le ore su pratiche attualmente completate comprendono anche quelle anteriori alla chiusura: non provano una modifica successiva.</p><button id="loadDataQuality" type="button">Verifica qualità dati</button><p id="qualityStatus" role="status"></p><div id="qualityGroups"></div><dialog id="qualityCaseDialog" class="quality-case"><h3>Dettaglio segnalazione</h3><div id="qualityCaseContent"></div><button id="qualityCaseJob" type="button" hidden>Apri pratica</button><button id="qualityCaseClose" type="button">Chiudi dettaglio</button></dialog>`;$("#adminPanel").appendChild(qualityHost);
const qualityGroups=new Map();let qualitySeq=0;
function clearQuality(){qualitySeq++;qualityGroups.clear();$("#qualityGroups").replaceChildren();$("#qualityCaseDialog").close();}
function renderQuality(){const open=new Set([...$("#qualityGroups").querySelectorAll("details[open]")].map(d=>d.dataset.kind));$("#qualityGroups").innerHTML=html`${[...qualityGroups.values()].map(g=>html`<details data-kind="${g.kind}" ${open.has(g.kind)?"open":""}><summary>${g.label}: ${g.count}</summary><p>${g.selectedCase?"Caso selezionato di "+g.count:g.count?`${g.offset+1}–${g.offset+g.rows.length} di ${g.count}`:"Nessun caso"}</p><div class="table-wrap"><table><thead><tr><th>Data</th><th>Tecnico</th><th>Caso</th><th>Ore</th><th>Dettaglio</th></tr></thead><tbody>${g.rows.map(r=>html`<tr><td>${r.date||"non indicato"}</td><td>${r.tecnicoNome||"non indicato"}</td><td>${r.title||r.id}</td><td>${r.minutes===undefined?"non indicato":fmtMinutes(r.minutes)}</td><td><a href="#quality/${g.kind}/${encodeURIComponent(r.id)}" data-quality-link>Apri caso</a></td></tr>`)}</tbody></table></div><button data-quality-kind="${g.kind}" data-quality-offset="${Math.max(0,g.offset-25)}" ${g.selectedCase||g.offset===0?"disabled":""}>Precedenti</button><button data-quality-kind="${g.kind}" data-quality-offset="${g.offset+25}" ${g.selectedCase||g.offset+g.rows.length>=g.count?"disabled":""}>Successivi</button></details>`)}`;
for(const button of $("#qualityGroups").querySelectorAll("[data-quality-kind]"))button.addEventListener("click",()=>loadDataQuality(button.dataset.qualityKind,Number(button.dataset.qualityOffset)));for(const link of $("#qualityGroups").querySelectorAll("[data-quality-link]"))link.addEventListener("click",e=>{e.preventDefault();history.replaceState(null,"",link.getAttribute("href"));followQualityLink();});}
async function loadDataQuality(kind="",offset=0,caseId=""){try{const seq=++qualitySeq;$("#qualityStatus").textContent="Verifica in corso…";const data=await api("dataQuality",{kind:kind||null,offset,limit:25,caseId:caseId||null});if(seq!==qualitySeq)return null;if(!kind)qualityGroups.clear();for(const g of data.groups||[])qualityGroups.set(g.kind,g);renderQuality();$("#qualityStatus").textContent="Verificato: "+new Date(data.checkedAt).toLocaleString("it-IT");return data;}catch(e){$("#qualityStatus").textContent="Verifica non completata.";notify(e.message);return null;}}
async function followQualityLink(){const match=location.hash.match(/^#quality\/([^/]+)\/(.+)$/);if(!match||profile?.ruolo!=="admin")return;let caseId;try{caseId=decodeURIComponent(match[2]);}catch{notify("Link segnalazione non valido.","warn");return;}$("#tabAdmin").click();qualityHost.open=true;const data=await loadDataQuality(match[1],0,caseId),row=data?.groups?.[0]?.rows?.find(r=>r.id===caseId);if(!row)return;const dialog=$("#qualityCaseDialog");$("#qualityCaseContent").innerHTML=html`<p><b>${row.title||row.id}</b></p><dl><dt>ID</dt><dd>${row.id}</dd><dt>Tecnico / UID</dt><dd>${row.tecnicoNome||"non indicato"} · ${row.tecnicoUid||"non indicato"}</dd><dt>Data</dt><dd>${row.date||"non indicato"}</dd><dt>Ore</dt><dd>${row.minutes===undefined?"non indicato":fmtMinutes(row.minutes)}</dd><dt>Assenza</dt><dd>${row.absenceMinutes===undefined?"non indicato":fmtMinutes(row.absenceMinutes)}</dd><dt>Inizio / fine</dt><dd>${row.start||"non indicato"} / ${row.end||"non indicato"}</dd><dt>Altri record sovrapposti</dt><dd>${(row.overlappingIds||[]).join(", ")||"non indicato"}</dd><dt>Fattori non indicati</dt><dd>${(row.missing||[]).join(", ")||"non indicato"}</dd></dl>${row.records?.length?html`<p>Registrazioni della giornata:</p><ul>${row.records.map(r=>html`<li>${r.id} · ${r.tipo_record||"non indicato"} · ${r.categoria||"non indicato"} · ${fmtMinutes(r.minutes)}</li>`)}</ul>`:""}`;const jobButton=$("#qualityCaseJob");jobButton.hidden=!row.jobId;jobButton.onclick=()=>{dialog.close();$("#tabArchive").click();openArchiveJob(row.jobId);};if(!dialog.open)dialog.showModal();}
$("#qualityCaseClose").addEventListener("click",()=>$("#qualityCaseDialog").close());$("#loadDataQuality").addEventListener("click",()=>loadDataQuality());window.addEventListener("hashchange",followQualityLink);
